Better paper broker
tfukaza/harvest pull request #126
Opened 2021-07-31 21:54 UTC by shershah010

on `order_limit` and `order_options_limit` set status to open and set status to filled on `fetch_stock_order_status`. Checks if the user can preform the purchase or sale before setting status to filled.

2021-07-31 21:57 UTC, shershah010 commented on harvest/api/paper.py
> +                    info(f'Limit price for {sym} is less than current price ({limit_price} < {price}).')
Check to see that the user can purchase the stocks and the price is lower than the limit_price.

2021-07-31 21:57 UTC, shershah010 commented on harvest/api/paper.py
> +                    ret['status'] = 'filled'
set the status to filled only if the stock was successfully bought.

2021-07-31 21:58 UTC, shershah010 commented on harvest/utils.py
> +    return date.tzinfo is not None and date.tzinfo.utcoffset(date) is not None
helper function to check if datetime object has tz info

2021-07-31 21:58 UTC, shershah010 commented on harvest/wizard.py
> -    def get_bool(self, prompt: str='y/n', true_pat:str=r'y|yes', false_path:str=r'n|no', default:str=None, persistent=True) -> bool:
fixed typo

2021-07-31 21:59 UTC, shershah010 commented on test/test_paper_broker.py
> +        order = dummy.order_limit('buy', 'A', 5, 50000)
set order limit to a high value to make sure that the order gets filled.

2021-07-31 21:59 UTC, shershah010 commented on test/test_wizard.py
> +# Builtins
tests for the wizard class.

2021-08-01 06:18 UTC, tfukaza requested changes

2021-08-01 06:18 UTC, tfukaza commented on harvest/api/paper.py
> +    def __init__(self, account_path: str=None, commission_fee: float=0.01):
Commission fees can be fixed (like options on [Ameritrade](https://www.tdameritrade.com/pricing.html)), or based on a percentage (like [Gemini](https://www.gemini.com/fees/api-fee-schedule#section-api-fee-schedule)), so ideally there should be a way to switch between that. Additionally, brokers can have different brokerage fees depending on the type of asset.

2021-08-03 04:35 UTC, shershah010 commented on harvest/api/paper.py
> +        """
The commission fee now supports flat prices and percentages and can distinguish between selling and buying assets,

2021-08-03 04:38 UTC, shershah010 commented on harvest/api/paper.py
> +    def apply_commission(self, inital_price: float, commission_fee, side: str) -> float:
applies a commission, the returned value is how much the user actually has to pay or actually receives after the commission is applied

2021-08-05 06:35 UTC, tfukaza commented
👍

2021-08-05 06:37 UTC, tfukaza approved these changes

2021-08-07 04:17 UTC, merged